<h5 class="darkblue"><a name="_site/loginAPI" class="anchor">&nbsp;</a>site/loginAPI</h5>
<b>Description</b>: login to GeoStockPhoto and get the session ID required to perform functions reserved to authenticated users.<br>
<b>Authentication</b>: not required.<br>
<b>Only for partners</b>: no.<br>
<b>Method</b>: post.<br>
<b>Protocol</b>: https.<br>

<table class="table table-bordered table-striped table-condensed" style="width:900px; margin-top: 10px">
	<thead class='bg_blue'>
		<tr>
			<td><b>Argument</b></td>
			<td><b>Type</b></td>
			<td style="width: 100px"><b>Valid Values</b></td>
			<td><b>Default Value</b></td>
			<td><b>Required</b></td>
			<td><b>Description</b></td>
		</tr>
	</thead>
	<tr>
		<td>username</td>
		<td>string</td>
		<td>existing username or email</td>
		<td>none</td>
		<td>yes</td>
		<td>Username or email of the user who wants to login to GeoStockPhoto.</td>
	</tr>
	<tr>
		<td>challenge</td>
		<td>string</td>
		<td>valid challenge</td>
		<td>none</td>
		<td>yes</td>
		<td>Challenge string returned by the <a href="#_site/getLoginChallenge">getLoginChallenge</a> function.</td>
	</tr>
	<tr>
		<td>cryptedpassword</td>
		<td>string</td>
		<td>see the Description field</td>
		<td>none</td>
		<td>yes</td>
		<td>String generated by the SHA512 encryption of the <i>&lt;challenge&gt;</i> (from the <a href="#_site/getLoginChallenge">getLoginChallenge</a> function),
			<i>&lt;clear_password&gt;</i> (your personal GeoStockPhoto password), <i>&lt;username&gt;</i> as:<br>
			SHA512(<i>&lt;challenge&gt;</i>+SHA512(<i>&lt;clear_password&gt;</i> + <i>&lt;username&gt;</i>))
		</td>
	</tr>
</table>

<table class="table table-bordered table-striped table-condensed" style="width:900px">
	<thead class='bg_blue'>
		<tr>
			<td><b>Returned Value</b></td>
			<td><b>Type</b></td>
			<td><b>Description</b></td>
		</tr>
	</thead>
	<!-- <tr>
		<td>SESSION_ID</td>
		<td>string</td>
		<td>Session id to be used in all functions that require authentication.</td>
	</tr> -->
	<tr>
		<td>SECURE_SESSION_ID</td>
		<td>string</td>
		<td>Secure session id to be used in some functions that require authentication via https.</td>
	</tr>
</table>